[package]
name = "ferrox"
version = "0.1.0"
edition = "2024"

[dependencies]
httpdate = "1"
rustls = { version = "0.23", optional = true }
tokio-rustls = { version = "0.26", optional = true }
rustls-pemfile = { version = "2", optional = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "signal", "fs"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
bytes = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
mime_guess = "2.0"
path-absolutize = "3.1"
sanitize-filename = "0.4"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }

[features]
tls = ["dep:rustls", "dep:tokio-rustls", "dep:rustls-pemfile"]
